#<?php die(0); ?>
table: group
fields:
	-id_group: int
	+name: string
	cathegory_list: bool
	cathegory_edit: bool
	cathegory_del: bool
	post_list: bool
	post_edit: bool
	post_del: bool
	gallery_list: bool
	gallery_edit: bool
	gallery_del: bool
	page_list: bool
	page_edit: bool
	page_del: bool
	anquette_list: bool
	anquette_edit: bool
	anquette_del: bool
	citation_list: bool
	citation_edit: bool
	citation_del: bool
	user_list: bool
	user_edit: bool
	user_del: bool
	group_list: bool
	group_edit: bool
	group_del: bool
	basic_list: bool
	advanced_list: bool
ids: id_group
